<?php
/**
 * CitiesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  GeoSearch
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GeoSearch
 *
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GeoSearch\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use GeoSearch\ApiException;
use GeoSearch\Configuration;
use GeoSearch\FormDataProcessor;
use GeoSearch\HeaderSelector;
use GeoSearch\ObjectSerializer;

/**
 * CitiesApi Class Doc Comment
 *
 * @category Class
 * @package  GeoSearch
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CitiesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'cityHierarchy' => [
            'application/json',
        ],
        'getCity' => [
            'application/json',
        ],
        'listCities' => [
            'application/json',
        ],
        'nearbyCities' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation cityHierarchy
     *
     * Get administrative hierarchy for a city
     *
     * @param  int $id City ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cityHierarchy'] to see the possible values for this operation
     *
     * @throws \GeoSearch\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoSearch\Model\HierarchyListResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse
     */
    public function cityHierarchy($id, $lang = null, string $contentType = self::contentTypes['cityHierarchy'][0])
    {
        list($response) = $this->cityHierarchyWithHttpInfo($id, $lang, $contentType);
        return $response;
    }

    /**
     * Operation cityHierarchyWithHttpInfo
     *
     * Get administrative hierarchy for a city
     *
     * @param  int $id City ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cityHierarchy'] to see the possible values for this operation
     *
     * @throws \GeoSearch\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoSearch\Model\HierarchyListResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function cityHierarchyWithHttpInfo($id, $lang = null, string $contentType = self::contentTypes['cityHierarchy'][0])
    {
        $request = $this->cityHierarchyRequest($id, $lang, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\HierarchyListResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoSearch\Model\HierarchyListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\HierarchyListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation cityHierarchyAsync
     *
     * Get administrative hierarchy for a city
     *
     * @param  int $id City ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cityHierarchy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cityHierarchyAsync($id, $lang = null, string $contentType = self::contentTypes['cityHierarchy'][0])
    {
        return $this->cityHierarchyAsyncWithHttpInfo($id, $lang, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation cityHierarchyAsyncWithHttpInfo
     *
     * Get administrative hierarchy for a city
     *
     * @param  int $id City ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cityHierarchy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function cityHierarchyAsyncWithHttpInfo($id, $lang = null, string $contentType = self::contentTypes['cityHierarchy'][0])
    {
        $returnType = '\GeoSearch\Model\HierarchyListResponse';
        $request = $this->cityHierarchyRequest($id, $lang, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'cityHierarchy'
     *
     * @param  int $id City ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['cityHierarchy'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function cityHierarchyRequest($id, $lang = null, string $contentType = self::contentTypes['cityHierarchy'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling cityHierarchy'
            );
        }

        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CitiesApi.cityHierarchy, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CitiesApi.cityHierarchy, must be bigger than or equal to 2.');
        }
        

        $resourcePath = '/v1/cities/{id}/hierarchy';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCity
     *
     * Get city by ID
     *
     * @param  int $id City ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCity'] to see the possible values for this operation
     *
     * @throws \GeoSearch\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoSearch\Model\CitySingleResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse
     */
    public function getCity($id, $lang = null, $fields = null, string $contentType = self::contentTypes['getCity'][0])
    {
        list($response) = $this->getCityWithHttpInfo($id, $lang, $fields, $contentType);
        return $response;
    }

    /**
     * Operation getCityWithHttpInfo
     *
     * Get city by ID
     *
     * @param  int $id City ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCity'] to see the possible values for this operation
     *
     * @throws \GeoSearch\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoSearch\Model\CitySingleResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCityWithHttpInfo($id, $lang = null, $fields = null, string $contentType = self::contentTypes['getCity'][0])
    {
        $request = $this->getCityRequest($id, $lang, $fields, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\CitySingleResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoSearch\Model\CitySingleResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\CitySingleResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getCityAsync
     *
     * Get city by ID
     *
     * @param  int $id City ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCity'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCityAsync($id, $lang = null, $fields = null, string $contentType = self::contentTypes['getCity'][0])
    {
        return $this->getCityAsyncWithHttpInfo($id, $lang, $fields, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCityAsyncWithHttpInfo
     *
     * Get city by ID
     *
     * @param  int $id City ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCity'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCityAsyncWithHttpInfo($id, $lang = null, $fields = null, string $contentType = self::contentTypes['getCity'][0])
    {
        $returnType = '\GeoSearch\Model\CitySingleResponse';
        $request = $this->getCityRequest($id, $lang, $fields, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCity'
     *
     * @param  int $id City ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCity'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCityRequest($id, $lang = null, $fields = null, string $contentType = self::contentTypes['getCity'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getCity'
            );
        }

        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CitiesApi.getCity, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CitiesApi.getCity, must be bigger than or equal to 2.');
        }
        


        $resourcePath = '/v1/cities/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listCities
     *
     * List cities
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $country Filter by ISO alpha-2 country codes (comma-separated) (optional)
     * @param  string|null $admin1 Filter by admin1 code (state/province) (optional)
     * @param  string|null $name Filter by city name (trigram fuzzy search) (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $timezone Filter by IANA timezone ID (optional)
     * @param  int|null $min_elevation Minimum elevation in meters (optional)
     * @param  int|null $max_elevation Maximum elevation in meters (optional)
     * @param  int|null $within Return only results whose coordinates fall geometrically inside the boundary of the given area, identified by its GeoNames id. Countries and administrative regions are valid areas; a city id is not.  Accepts exactly one id. A COMMA-SEPARATED LIST IS REJECTED with a 422 naming the limit — a deliberate departure from the comma-separated convention &#x60;country&#x60; uses, because each value would be a separate polygon intersection. Ask for one area per request.  COST: a request using this parameter consumes 2 quota units instead of 1, on every plan including Free. Combining it with &#x60;bbox&#x60; still costs 2, not 3 — the highest multiplier applies rather than the sum, and adding a box makes the query cheaper to serve, so it is never penalised.  This asks a GEOMETRIC question and can therefore return a different set of cities than &#x60;/v1/regions/{id}/cities&#x60;, which asks an administrative one. See that endpoint&#39;s description for when and why the two disagree.  Two failures are reported with distinct 400 codes so a typo is distinguishable from a coverage gap: &#x60;area_not_an_area&#x60; means the id does not name a country or region at all, and &#x60;area_no_boundary&#x60; means it does but no boundary polygon is available for it yet. (optional)
     * @param  string|null $bbox Return only results inside the bounding box, given as four comma-separated numbers in the order &#x60;w,s,e,n&#x60; — west longitude, south latitude, east longitude, north latitude.  Longitudes must be within [-180, 180] and latitudes within [-90, 90].  A box where WEST IS GREATER THAN EAST wraps the antimeridian and is fully supported: &#x60;bbox&#x3D;170,-20,-170,-10&#x60; is a box around Fiji, evaluated as the union of the two halves it spans. Latitude has no equivalent wrap-around meaning, so &#x60;s&#x60; greater than &#x60;n&#x60; is a validation error rather than a wrapped box.  Charged at the standard request cost of 1 unit. Adding it to a &#x60;within&#x60; query narrows the candidate set before the polygon test and does not raise the charge. (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population, elevation, id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCities'] to see the possible values for this operation
     *
     * @throws \GeoSearch\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoSearch\Model\CityListResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse
     */
    public function listCities($lang = null, $country = null, $admin1 = null, $name = null, $population_min = null, $population_max = null, $timezone = null, $min_elevation = null, $max_elevation = null, $within = null, $bbox = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCities'][0])
    {
        list($response) = $this->listCitiesWithHttpInfo($lang, $country, $admin1, $name, $population_min, $population_max, $timezone, $min_elevation, $max_elevation, $within, $bbox, $cursor, $limit, $fields, $sort, $contentType);
        return $response;
    }

    /**
     * Operation listCitiesWithHttpInfo
     *
     * List cities
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $country Filter by ISO alpha-2 country codes (comma-separated) (optional)
     * @param  string|null $admin1 Filter by admin1 code (state/province) (optional)
     * @param  string|null $name Filter by city name (trigram fuzzy search) (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $timezone Filter by IANA timezone ID (optional)
     * @param  int|null $min_elevation Minimum elevation in meters (optional)
     * @param  int|null $max_elevation Maximum elevation in meters (optional)
     * @param  int|null $within Return only results whose coordinates fall geometrically inside the boundary of the given area, identified by its GeoNames id. Countries and administrative regions are valid areas; a city id is not.  Accepts exactly one id. A COMMA-SEPARATED LIST IS REJECTED with a 422 naming the limit — a deliberate departure from the comma-separated convention &#x60;country&#x60; uses, because each value would be a separate polygon intersection. Ask for one area per request.  COST: a request using this parameter consumes 2 quota units instead of 1, on every plan including Free. Combining it with &#x60;bbox&#x60; still costs 2, not 3 — the highest multiplier applies rather than the sum, and adding a box makes the query cheaper to serve, so it is never penalised.  This asks a GEOMETRIC question and can therefore return a different set of cities than &#x60;/v1/regions/{id}/cities&#x60;, which asks an administrative one. See that endpoint&#39;s description for when and why the two disagree.  Two failures are reported with distinct 400 codes so a typo is distinguishable from a coverage gap: &#x60;area_not_an_area&#x60; means the id does not name a country or region at all, and &#x60;area_no_boundary&#x60; means it does but no boundary polygon is available for it yet. (optional)
     * @param  string|null $bbox Return only results inside the bounding box, given as four comma-separated numbers in the order &#x60;w,s,e,n&#x60; — west longitude, south latitude, east longitude, north latitude.  Longitudes must be within [-180, 180] and latitudes within [-90, 90].  A box where WEST IS GREATER THAN EAST wraps the antimeridian and is fully supported: &#x60;bbox&#x3D;170,-20,-170,-10&#x60; is a box around Fiji, evaluated as the union of the two halves it spans. Latitude has no equivalent wrap-around meaning, so &#x60;s&#x60; greater than &#x60;n&#x60; is a validation error rather than a wrapped box.  Charged at the standard request cost of 1 unit. Adding it to a &#x60;within&#x60; query narrows the candidate set before the polygon test and does not raise the charge. (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population, elevation, id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCities'] to see the possible values for this operation
     *
     * @throws \GeoSearch\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoSearch\Model\CityListResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listCitiesWithHttpInfo($lang = null, $country = null, $admin1 = null, $name = null, $population_min = null, $population_max = null, $timezone = null, $min_elevation = null, $max_elevation = null, $within = null, $bbox = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCities'][0])
    {
        $request = $this->listCitiesRequest($lang, $country, $admin1, $name, $population_min, $population_max, $timezone, $min_elevation, $max_elevation, $within, $bbox, $cursor, $limit, $fields, $sort, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\CityListResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoSearch\Model\CityListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\CityListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listCitiesAsync
     *
     * List cities
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $country Filter by ISO alpha-2 country codes (comma-separated) (optional)
     * @param  string|null $admin1 Filter by admin1 code (state/province) (optional)
     * @param  string|null $name Filter by city name (trigram fuzzy search) (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $timezone Filter by IANA timezone ID (optional)
     * @param  int|null $min_elevation Minimum elevation in meters (optional)
     * @param  int|null $max_elevation Maximum elevation in meters (optional)
     * @param  int|null $within Return only results whose coordinates fall geometrically inside the boundary of the given area, identified by its GeoNames id. Countries and administrative regions are valid areas; a city id is not.  Accepts exactly one id. A COMMA-SEPARATED LIST IS REJECTED with a 422 naming the limit — a deliberate departure from the comma-separated convention &#x60;country&#x60; uses, because each value would be a separate polygon intersection. Ask for one area per request.  COST: a request using this parameter consumes 2 quota units instead of 1, on every plan including Free. Combining it with &#x60;bbox&#x60; still costs 2, not 3 — the highest multiplier applies rather than the sum, and adding a box makes the query cheaper to serve, so it is never penalised.  This asks a GEOMETRIC question and can therefore return a different set of cities than &#x60;/v1/regions/{id}/cities&#x60;, which asks an administrative one. See that endpoint&#39;s description for when and why the two disagree.  Two failures are reported with distinct 400 codes so a typo is distinguishable from a coverage gap: &#x60;area_not_an_area&#x60; means the id does not name a country or region at all, and &#x60;area_no_boundary&#x60; means it does but no boundary polygon is available for it yet. (optional)
     * @param  string|null $bbox Return only results inside the bounding box, given as four comma-separated numbers in the order &#x60;w,s,e,n&#x60; — west longitude, south latitude, east longitude, north latitude.  Longitudes must be within [-180, 180] and latitudes within [-90, 90].  A box where WEST IS GREATER THAN EAST wraps the antimeridian and is fully supported: &#x60;bbox&#x3D;170,-20,-170,-10&#x60; is a box around Fiji, evaluated as the union of the two halves it spans. Latitude has no equivalent wrap-around meaning, so &#x60;s&#x60; greater than &#x60;n&#x60; is a validation error rather than a wrapped box.  Charged at the standard request cost of 1 unit. Adding it to a &#x60;within&#x60; query narrows the candidate set before the polygon test and does not raise the charge. (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population, elevation, id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCitiesAsync($lang = null, $country = null, $admin1 = null, $name = null, $population_min = null, $population_max = null, $timezone = null, $min_elevation = null, $max_elevation = null, $within = null, $bbox = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCities'][0])
    {
        return $this->listCitiesAsyncWithHttpInfo($lang, $country, $admin1, $name, $population_min, $population_max, $timezone, $min_elevation, $max_elevation, $within, $bbox, $cursor, $limit, $fields, $sort, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listCitiesAsyncWithHttpInfo
     *
     * List cities
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $country Filter by ISO alpha-2 country codes (comma-separated) (optional)
     * @param  string|null $admin1 Filter by admin1 code (state/province) (optional)
     * @param  string|null $name Filter by city name (trigram fuzzy search) (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $timezone Filter by IANA timezone ID (optional)
     * @param  int|null $min_elevation Minimum elevation in meters (optional)
     * @param  int|null $max_elevation Maximum elevation in meters (optional)
     * @param  int|null $within Return only results whose coordinates fall geometrically inside the boundary of the given area, identified by its GeoNames id. Countries and administrative regions are valid areas; a city id is not.  Accepts exactly one id. A COMMA-SEPARATED LIST IS REJECTED with a 422 naming the limit — a deliberate departure from the comma-separated convention &#x60;country&#x60; uses, because each value would be a separate polygon intersection. Ask for one area per request.  COST: a request using this parameter consumes 2 quota units instead of 1, on every plan including Free. Combining it with &#x60;bbox&#x60; still costs 2, not 3 — the highest multiplier applies rather than the sum, and adding a box makes the query cheaper to serve, so it is never penalised.  This asks a GEOMETRIC question and can therefore return a different set of cities than &#x60;/v1/regions/{id}/cities&#x60;, which asks an administrative one. See that endpoint&#39;s description for when and why the two disagree.  Two failures are reported with distinct 400 codes so a typo is distinguishable from a coverage gap: &#x60;area_not_an_area&#x60; means the id does not name a country or region at all, and &#x60;area_no_boundary&#x60; means it does but no boundary polygon is available for it yet. (optional)
     * @param  string|null $bbox Return only results inside the bounding box, given as four comma-separated numbers in the order &#x60;w,s,e,n&#x60; — west longitude, south latitude, east longitude, north latitude.  Longitudes must be within [-180, 180] and latitudes within [-90, 90].  A box where WEST IS GREATER THAN EAST wraps the antimeridian and is fully supported: &#x60;bbox&#x3D;170,-20,-170,-10&#x60; is a box around Fiji, evaluated as the union of the two halves it spans. Latitude has no equivalent wrap-around meaning, so &#x60;s&#x60; greater than &#x60;n&#x60; is a validation error rather than a wrapped box.  Charged at the standard request cost of 1 unit. Adding it to a &#x60;within&#x60; query narrows the candidate set before the polygon test and does not raise the charge. (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population, elevation, id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCitiesAsyncWithHttpInfo($lang = null, $country = null, $admin1 = null, $name = null, $population_min = null, $population_max = null, $timezone = null, $min_elevation = null, $max_elevation = null, $within = null, $bbox = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCities'][0])
    {
        $returnType = '\GeoSearch\Model\CityListResponse';
        $request = $this->listCitiesRequest($lang, $country, $admin1, $name, $population_min, $population_max, $timezone, $min_elevation, $max_elevation, $within, $bbox, $cursor, $limit, $fields, $sort, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listCities'
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $country Filter by ISO alpha-2 country codes (comma-separated) (optional)
     * @param  string|null $admin1 Filter by admin1 code (state/province) (optional)
     * @param  string|null $name Filter by city name (trigram fuzzy search) (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $timezone Filter by IANA timezone ID (optional)
     * @param  int|null $min_elevation Minimum elevation in meters (optional)
     * @param  int|null $max_elevation Maximum elevation in meters (optional)
     * @param  int|null $within Return only results whose coordinates fall geometrically inside the boundary of the given area, identified by its GeoNames id. Countries and administrative regions are valid areas; a city id is not.  Accepts exactly one id. A COMMA-SEPARATED LIST IS REJECTED with a 422 naming the limit — a deliberate departure from the comma-separated convention &#x60;country&#x60; uses, because each value would be a separate polygon intersection. Ask for one area per request.  COST: a request using this parameter consumes 2 quota units instead of 1, on every plan including Free. Combining it with &#x60;bbox&#x60; still costs 2, not 3 — the highest multiplier applies rather than the sum, and adding a box makes the query cheaper to serve, so it is never penalised.  This asks a GEOMETRIC question and can therefore return a different set of cities than &#x60;/v1/regions/{id}/cities&#x60;, which asks an administrative one. See that endpoint&#39;s description for when and why the two disagree.  Two failures are reported with distinct 400 codes so a typo is distinguishable from a coverage gap: &#x60;area_not_an_area&#x60; means the id does not name a country or region at all, and &#x60;area_no_boundary&#x60; means it does but no boundary polygon is available for it yet. (optional)
     * @param  string|null $bbox Return only results inside the bounding box, given as four comma-separated numbers in the order &#x60;w,s,e,n&#x60; — west longitude, south latitude, east longitude, north latitude.  Longitudes must be within [-180, 180] and latitudes within [-90, 90].  A box where WEST IS GREATER THAN EAST wraps the antimeridian and is fully supported: &#x60;bbox&#x3D;170,-20,-170,-10&#x60; is a box around Fiji, evaluated as the union of the two halves it spans. Latitude has no equivalent wrap-around meaning, so &#x60;s&#x60; greater than &#x60;n&#x60; is a validation error rather than a wrapped box.  Charged at the standard request cost of 1 unit. Adding it to a &#x60;within&#x60; query narrows the candidate set before the polygon test and does not raise the charge. (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population, elevation, id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listCitiesRequest($lang = null, $country = null, $admin1 = null, $name = null, $population_min = null, $population_max = null, $timezone = null, $min_elevation = null, $max_elevation = null, $within = null, $bbox = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCities'][0])
    {

        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CitiesApi.listCities, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CitiesApi.listCities, must be bigger than or equal to 2.');
        }
        









        if ($bbox !== null && !preg_match("/^-?\\d+(\\.\\d+)?(,-?\\d+(\\.\\d+)?){3}$/", $bbox)) {
            throw new \InvalidArgumentException("invalid value for \"bbox\" when calling CitiesApi.listCities, must conform to the pattern /^-?\\d+(\\.\\d+)?(,-?\\d+(\\.\\d+)?){3}$/.");
        }
        

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling CitiesApi.listCities, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling CitiesApi.listCities, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/v1/cities';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $country,
            'country', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $admin1,
            'admin1', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $name,
            'name', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $population_min,
            'population_min', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $population_max,
            'population_max', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $timezone,
            'timezone', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $min_elevation,
            'min_elevation', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $max_elevation,
            'max_elevation', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $within,
            'within', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $bbox,
            'bbox', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation nearbyCities
     *
     * Find nearby cities
     *
     * @param  float $lat Latitude (-90 to 90) (required)
     * @param  float $lon Longitude (-180 to 180) (required)
     * @param  float|null $radius Search radius in kilometers (default 50, max 200) (optional, default to 50)
     * @param  int|null $limit Maximum results to return (1-250, default 10) (optional, default to 10)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nearbyCities'] to see the possible values for this operation
     *
     * @throws \GeoSearch\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoSearch\Model\NearbyCityListResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse
     */
    public function nearbyCities($lat, $lon, $radius = 50, $limit = 10, $fields = null, string $contentType = self::contentTypes['nearbyCities'][0])
    {
        list($response) = $this->nearbyCitiesWithHttpInfo($lat, $lon, $radius, $limit, $fields, $contentType);
        return $response;
    }

    /**
     * Operation nearbyCitiesWithHttpInfo
     *
     * Find nearby cities
     *
     * @param  float $lat Latitude (-90 to 90) (required)
     * @param  float $lon Longitude (-180 to 180) (required)
     * @param  float|null $radius Search radius in kilometers (default 50, max 200) (optional, default to 50)
     * @param  int|null $limit Maximum results to return (1-250, default 10) (optional, default to 10)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nearbyCities'] to see the possible values for this operation
     *
     * @throws \GeoSearch\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoSearch\Model\NearbyCityListResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse|\GeoSearch\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function nearbyCitiesWithHttpInfo($lat, $lon, $radius = 50, $limit = 10, $fields = null, string $contentType = self::contentTypes['nearbyCities'][0])
    {
        $request = $this->nearbyCitiesRequest($lat, $lon, $radius, $limit, $fields, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\NearbyCityListResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoSearch\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoSearch\Model\NearbyCityListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\NearbyCityListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoSearch\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation nearbyCitiesAsync
     *
     * Find nearby cities
     *
     * @param  float $lat Latitude (-90 to 90) (required)
     * @param  float $lon Longitude (-180 to 180) (required)
     * @param  float|null $radius Search radius in kilometers (default 50, max 200) (optional, default to 50)
     * @param  int|null $limit Maximum results to return (1-250, default 10) (optional, default to 10)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nearbyCities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nearbyCitiesAsync($lat, $lon, $radius = 50, $limit = 10, $fields = null, string $contentType = self::contentTypes['nearbyCities'][0])
    {
        return $this->nearbyCitiesAsyncWithHttpInfo($lat, $lon, $radius, $limit, $fields, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation nearbyCitiesAsyncWithHttpInfo
     *
     * Find nearby cities
     *
     * @param  float $lat Latitude (-90 to 90) (required)
     * @param  float $lon Longitude (-180 to 180) (required)
     * @param  float|null $radius Search radius in kilometers (default 50, max 200) (optional, default to 50)
     * @param  int|null $limit Maximum results to return (1-250, default 10) (optional, default to 10)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nearbyCities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function nearbyCitiesAsyncWithHttpInfo($lat, $lon, $radius = 50, $limit = 10, $fields = null, string $contentType = self::contentTypes['nearbyCities'][0])
    {
        $returnType = '\GeoSearch\Model\NearbyCityListResponse';
        $request = $this->nearbyCitiesRequest($lat, $lon, $radius, $limit, $fields, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'nearbyCities'
     *
     * @param  float $lat Latitude (-90 to 90) (required)
     * @param  float $lon Longitude (-180 to 180) (required)
     * @param  float|null $radius Search radius in kilometers (default 50, max 200) (optional, default to 50)
     * @param  int|null $limit Maximum results to return (1-250, default 10) (optional, default to 10)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['nearbyCities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function nearbyCitiesRequest($lat, $lon, $radius = 50, $limit = 10, $fields = null, string $contentType = self::contentTypes['nearbyCities'][0])
    {

        // verify the required parameter 'lat' is set
        if ($lat === null || (is_array($lat) && count($lat) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lat when calling nearbyCities'
            );
        }
        if ($lat > 90) {
            throw new \InvalidArgumentException('invalid value for "$lat" when calling CitiesApi.nearbyCities, must be smaller than or equal to 90.');
        }
        if ($lat < -90) {
            throw new \InvalidArgumentException('invalid value for "$lat" when calling CitiesApi.nearbyCities, must be bigger than or equal to -90.');
        }
        
        // verify the required parameter 'lon' is set
        if ($lon === null || (is_array($lon) && count($lon) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lon when calling nearbyCities'
            );
        }
        if ($lon > 180) {
            throw new \InvalidArgumentException('invalid value for "$lon" when calling CitiesApi.nearbyCities, must be smaller than or equal to 180.');
        }
        if ($lon < -180) {
            throw new \InvalidArgumentException('invalid value for "$lon" when calling CitiesApi.nearbyCities, must be bigger than or equal to -180.');
        }
        
        if ($radius !== null && $radius > 200) {
            throw new \InvalidArgumentException('invalid value for "$radius" when calling CitiesApi.nearbyCities, must be smaller than or equal to 200.');
        }
        if ($radius !== null && $radius < 0) {
            throw new \InvalidArgumentException('invalid value for "$radius" when calling CitiesApi.nearbyCities, must be bigger than or equal to 0.');
        }
        
        if ($limit !== null && $limit > 250) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling CitiesApi.nearbyCities, must be smaller than or equal to 250.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling CitiesApi.nearbyCities, must be bigger than or equal to 1.');
        }
        


        $resourcePath = '/v1/cities/nearby';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lat,
            'lat', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lon,
            'lon', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $radius,
            'radius', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
