<?php
/**
 * CountriesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  GeoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GeoAPI
 *
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GeoAPI\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use GeoAPI\ApiException;
use GeoAPI\Configuration;
use GeoAPI\FormDataProcessor;
use GeoAPI\HeaderSelector;
use GeoAPI\ObjectSerializer;

/**
 * CountriesApi Class Doc Comment
 *
 * @category Class
 * @package  GeoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CountriesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'countryNeighbors' => [
            'application/json',
        ],
        'getCountry' => [
            'application/json',
        ],
        'listCountries' => [
            'application/json',
        ],
        'listCountryRegions' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation countryNeighbors
     *
     * List neighboring countries
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['countryNeighbors'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoAPI\Model\CountryListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse
     */
    public function countryNeighbors($code, $lang = null, $fields = null, string $contentType = self::contentTypes['countryNeighbors'][0])
    {
        list($response) = $this->countryNeighborsWithHttpInfo($code, $lang, $fields, $contentType);
        return $response;
    }

    /**
     * Operation countryNeighborsWithHttpInfo
     *
     * List neighboring countries
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['countryNeighbors'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoAPI\Model\CountryListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function countryNeighborsWithHttpInfo($code, $lang = null, $fields = null, string $contentType = self::contentTypes['countryNeighbors'][0])
    {
        $request = $this->countryNeighborsRequest($code, $lang, $fields, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\CountryListResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoAPI\Model\CountryListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\CountryListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation countryNeighborsAsync
     *
     * List neighboring countries
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['countryNeighbors'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function countryNeighborsAsync($code, $lang = null, $fields = null, string $contentType = self::contentTypes['countryNeighbors'][0])
    {
        return $this->countryNeighborsAsyncWithHttpInfo($code, $lang, $fields, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation countryNeighborsAsyncWithHttpInfo
     *
     * List neighboring countries
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['countryNeighbors'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function countryNeighborsAsyncWithHttpInfo($code, $lang = null, $fields = null, string $contentType = self::contentTypes['countryNeighbors'][0])
    {
        $returnType = '\GeoAPI\Model\CountryListResponse';
        $request = $this->countryNeighborsRequest($code, $lang, $fields, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'countryNeighbors'
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['countryNeighbors'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function countryNeighborsRequest($code, $lang = null, $fields = null, string $contentType = self::contentTypes['countryNeighbors'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling countryNeighbors'
            );
        }
        if (strlen($code) > 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling CountriesApi.countryNeighbors, must be smaller than or equal to 2.');
        }
        if (strlen($code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling CountriesApi.countryNeighbors, must be bigger than or equal to 2.');
        }
        
        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CountriesApi.countryNeighbors, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CountriesApi.countryNeighbors, must be bigger than or equal to 2.');
        }
        


        $resourcePath = '/v1/countries/{code}/neighbors';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCountry
     *
     * Get country by ISO code
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCountry'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoAPI\Model\CountrySingleResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse
     */
    public function getCountry($code, $lang = null, $fields = null, string $contentType = self::contentTypes['getCountry'][0])
    {
        list($response) = $this->getCountryWithHttpInfo($code, $lang, $fields, $contentType);
        return $response;
    }

    /**
     * Operation getCountryWithHttpInfo
     *
     * Get country by ISO code
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCountry'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoAPI\Model\CountrySingleResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCountryWithHttpInfo($code, $lang = null, $fields = null, string $contentType = self::contentTypes['getCountry'][0])
    {
        $request = $this->getCountryRequest($code, $lang, $fields, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\CountrySingleResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoAPI\Model\CountrySingleResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\CountrySingleResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getCountryAsync
     *
     * Get country by ISO code
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCountry'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCountryAsync($code, $lang = null, $fields = null, string $contentType = self::contentTypes['getCountry'][0])
    {
        return $this->getCountryAsyncWithHttpInfo($code, $lang, $fields, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCountryAsyncWithHttpInfo
     *
     * Get country by ISO code
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCountry'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCountryAsyncWithHttpInfo($code, $lang = null, $fields = null, string $contentType = self::contentTypes['getCountry'][0])
    {
        $returnType = '\GeoAPI\Model\CountrySingleResponse';
        $request = $this->getCountryRequest($code, $lang, $fields, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCountry'
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCountry'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCountryRequest($code, $lang = null, $fields = null, string $contentType = self::contentTypes['getCountry'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling getCountry'
            );
        }
        if (strlen($code) > 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling CountriesApi.getCountry, must be smaller than or equal to 2.');
        }
        if (strlen($code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling CountriesApi.getCountry, must be bigger than or equal to 2.');
        }
        
        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CountriesApi.getCountry, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CountriesApi.getCountry, must be bigger than or equal to 2.');
        }
        


        $resourcePath = '/v1/countries/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listCountries
     *
     * List countries
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $continent Filter by continent code (AF, AN, AS, EU, NA, OC, SA) (optional)
     * @param  string|null $iso_code Filter by ISO alpha-2 codes (comma-separated) (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field and direction. Allowed: name, population, area_sq_km. Prefix with - for descending. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCountries'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoAPI\Model\CountryListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse
     */
    public function listCountries($lang = null, $continent = null, $iso_code = null, $population_min = null, $population_max = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCountries'][0])
    {
        list($response) = $this->listCountriesWithHttpInfo($lang, $continent, $iso_code, $population_min, $population_max, $cursor, $limit, $fields, $sort, $contentType);
        return $response;
    }

    /**
     * Operation listCountriesWithHttpInfo
     *
     * List countries
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $continent Filter by continent code (AF, AN, AS, EU, NA, OC, SA) (optional)
     * @param  string|null $iso_code Filter by ISO alpha-2 codes (comma-separated) (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field and direction. Allowed: name, population, area_sq_km. Prefix with - for descending. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCountries'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoAPI\Model\CountryListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listCountriesWithHttpInfo($lang = null, $continent = null, $iso_code = null, $population_min = null, $population_max = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCountries'][0])
    {
        $request = $this->listCountriesRequest($lang, $continent, $iso_code, $population_min, $population_max, $cursor, $limit, $fields, $sort, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\CountryListResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoAPI\Model\CountryListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\CountryListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listCountriesAsync
     *
     * List countries
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $continent Filter by continent code (AF, AN, AS, EU, NA, OC, SA) (optional)
     * @param  string|null $iso_code Filter by ISO alpha-2 codes (comma-separated) (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field and direction. Allowed: name, population, area_sq_km. Prefix with - for descending. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCountries'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCountriesAsync($lang = null, $continent = null, $iso_code = null, $population_min = null, $population_max = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCountries'][0])
    {
        return $this->listCountriesAsyncWithHttpInfo($lang, $continent, $iso_code, $population_min, $population_max, $cursor, $limit, $fields, $sort, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listCountriesAsyncWithHttpInfo
     *
     * List countries
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $continent Filter by continent code (AF, AN, AS, EU, NA, OC, SA) (optional)
     * @param  string|null $iso_code Filter by ISO alpha-2 codes (comma-separated) (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field and direction. Allowed: name, population, area_sq_km. Prefix with - for descending. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCountries'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCountriesAsyncWithHttpInfo($lang = null, $continent = null, $iso_code = null, $population_min = null, $population_max = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCountries'][0])
    {
        $returnType = '\GeoAPI\Model\CountryListResponse';
        $request = $this->listCountriesRequest($lang, $continent, $iso_code, $population_min, $population_max, $cursor, $limit, $fields, $sort, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listCountries'
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $continent Filter by continent code (AF, AN, AS, EU, NA, OC, SA) (optional)
     * @param  string|null $iso_code Filter by ISO alpha-2 codes (comma-separated) (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field and direction. Allowed: name, population, area_sq_km. Prefix with - for descending. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCountries'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listCountriesRequest($lang = null, $continent = null, $iso_code = null, $population_min = null, $population_max = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCountries'][0])
    {

        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CountriesApi.listCountries, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CountriesApi.listCountries, must be bigger than or equal to 2.');
        }
        





        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling CountriesApi.listCountries, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling CountriesApi.listCountries, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/v1/countries';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $continent,
            'continent', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $iso_code,
            'iso_code', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $population_min,
            'population_min', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $population_max,
            'population_max', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listCountryRegions
     *
     * List regions in a country
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCountryRegions'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoAPI\Model\RegionListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse
     */
    public function listCountryRegions($code, $lang = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCountryRegions'][0])
    {
        list($response) = $this->listCountryRegionsWithHttpInfo($code, $lang, $cursor, $limit, $fields, $sort, $contentType);
        return $response;
    }

    /**
     * Operation listCountryRegionsWithHttpInfo
     *
     * List regions in a country
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCountryRegions'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoAPI\Model\RegionListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listCountryRegionsWithHttpInfo($code, $lang = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCountryRegions'][0])
    {
        $request = $this->listCountryRegionsRequest($code, $lang, $cursor, $limit, $fields, $sort, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\RegionListResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoAPI\Model\RegionListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\RegionListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listCountryRegionsAsync
     *
     * List regions in a country
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCountryRegions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCountryRegionsAsync($code, $lang = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCountryRegions'][0])
    {
        return $this->listCountryRegionsAsyncWithHttpInfo($code, $lang, $cursor, $limit, $fields, $sort, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listCountryRegionsAsyncWithHttpInfo
     *
     * List regions in a country
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCountryRegions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCountryRegionsAsyncWithHttpInfo($code, $lang = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCountryRegions'][0])
    {
        $returnType = '\GeoAPI\Model\RegionListResponse';
        $request = $this->listCountryRegionsRequest($code, $lang, $cursor, $limit, $fields, $sort, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listCountryRegions'
     *
     * @param  string $code ISO alpha-2 country code (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listCountryRegions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listCountryRegionsRequest($code, $lang = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listCountryRegions'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling listCountryRegions'
            );
        }

        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CountriesApi.listCountryRegions, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling CountriesApi.listCountryRegions, must be bigger than or equal to 2.');
        }
        

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling CountriesApi.listCountryRegions, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling CountriesApi.listCountryRegions, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/v1/countries/{code}/regions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
