<?php
/**
 * RegionsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  GeoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GeoAPI
 *
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields.
 *
 * The version of the OpenAPI document: 1.2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GeoAPI\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use GeoAPI\ApiException;
use GeoAPI\Configuration;
use GeoAPI\FormDataProcessor;
use GeoAPI\HeaderSelector;
use GeoAPI\ObjectSerializer;

/**
 * RegionsApi Class Doc Comment
 *
 * @category Class
 * @package  GeoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RegionsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getRegion' => [
            'application/json',
        ],
        'listRegionCities' => [
            'application/json',
        ],
        'listRegions' => [
            'application/json',
        ],
        'regionChildren' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getRegion
     *
     * Get region by ID
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRegion'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoAPI\Model\RegionSingleResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse
     */
    public function getRegion($id, $lang = null, $fields = null, string $contentType = self::contentTypes['getRegion'][0])
    {
        list($response) = $this->getRegionWithHttpInfo($id, $lang, $fields, $contentType);
        return $response;
    }

    /**
     * Operation getRegionWithHttpInfo
     *
     * Get region by ID
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRegion'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoAPI\Model\RegionSingleResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getRegionWithHttpInfo($id, $lang = null, $fields = null, string $contentType = self::contentTypes['getRegion'][0])
    {
        $request = $this->getRegionRequest($id, $lang, $fields, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\RegionSingleResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoAPI\Model\RegionSingleResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\RegionSingleResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getRegionAsync
     *
     * Get region by ID
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRegion'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRegionAsync($id, $lang = null, $fields = null, string $contentType = self::contentTypes['getRegion'][0])
    {
        return $this->getRegionAsyncWithHttpInfo($id, $lang, $fields, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getRegionAsyncWithHttpInfo
     *
     * Get region by ID
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRegion'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRegionAsyncWithHttpInfo($id, $lang = null, $fields = null, string $contentType = self::contentTypes['getRegion'][0])
    {
        $returnType = '\GeoAPI\Model\RegionSingleResponse';
        $request = $this->getRegionRequest($id, $lang, $fields, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getRegion'
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRegion'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getRegionRequest($id, $lang = null, $fields = null, string $contentType = self::contentTypes['getRegion'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getRegion'
            );
        }

        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling RegionsApi.getRegion, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling RegionsApi.getRegion, must be bigger than or equal to 2.');
        }
        


        $resourcePath = '/v1/regions/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listRegionCities
     *
     * List cities in a region
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRegionCities'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoAPI\Model\CityListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse
     */
    public function listRegionCities($id, $lang = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listRegionCities'][0])
    {
        list($response) = $this->listRegionCitiesWithHttpInfo($id, $lang, $cursor, $limit, $fields, $sort, $contentType);
        return $response;
    }

    /**
     * Operation listRegionCitiesWithHttpInfo
     *
     * List cities in a region
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRegionCities'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoAPI\Model\CityListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listRegionCitiesWithHttpInfo($id, $lang = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listRegionCities'][0])
    {
        $request = $this->listRegionCitiesRequest($id, $lang, $cursor, $limit, $fields, $sort, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\CityListResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoAPI\Model\CityListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\CityListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listRegionCitiesAsync
     *
     * List cities in a region
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRegionCities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listRegionCitiesAsync($id, $lang = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listRegionCities'][0])
    {
        return $this->listRegionCitiesAsyncWithHttpInfo($id, $lang, $cursor, $limit, $fields, $sort, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listRegionCitiesAsyncWithHttpInfo
     *
     * List cities in a region
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRegionCities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listRegionCitiesAsyncWithHttpInfo($id, $lang = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listRegionCities'][0])
    {
        $returnType = '\GeoAPI\Model\CityListResponse';
        $request = $this->listRegionCitiesRequest($id, $lang, $cursor, $limit, $fields, $sort, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listRegionCities'
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRegionCities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listRegionCitiesRequest($id, $lang = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listRegionCities'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling listRegionCities'
            );
        }

        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling RegionsApi.listRegionCities, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling RegionsApi.listRegionCities, must be bigger than or equal to 2.');
        }
        

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling RegionsApi.listRegionCities, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling RegionsApi.listRegionCities, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/v1/regions/{id}/cities';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listRegions
     *
     * List regions
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $country Filter by ISO alpha-2 country code (optional)
     * @param  int|null $level Filter by administrative level (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRegions'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoAPI\Model\RegionListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse
     */
    public function listRegions($lang = null, $country = null, $level = null, $population_min = null, $population_max = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listRegions'][0])
    {
        list($response) = $this->listRegionsWithHttpInfo($lang, $country, $level, $population_min, $population_max, $cursor, $limit, $fields, $sort, $contentType);
        return $response;
    }

    /**
     * Operation listRegionsWithHttpInfo
     *
     * List regions
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $country Filter by ISO alpha-2 country code (optional)
     * @param  int|null $level Filter by administrative level (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRegions'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoAPI\Model\RegionListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listRegionsWithHttpInfo($lang = null, $country = null, $level = null, $population_min = null, $population_max = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listRegions'][0])
    {
        $request = $this->listRegionsRequest($lang, $country, $level, $population_min, $population_max, $cursor, $limit, $fields, $sort, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\RegionListResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoAPI\Model\RegionListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\RegionListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listRegionsAsync
     *
     * List regions
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $country Filter by ISO alpha-2 country code (optional)
     * @param  int|null $level Filter by administrative level (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRegions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listRegionsAsync($lang = null, $country = null, $level = null, $population_min = null, $population_max = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listRegions'][0])
    {
        return $this->listRegionsAsyncWithHttpInfo($lang, $country, $level, $population_min, $population_max, $cursor, $limit, $fields, $sort, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listRegionsAsyncWithHttpInfo
     *
     * List regions
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $country Filter by ISO alpha-2 country code (optional)
     * @param  int|null $level Filter by administrative level (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRegions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listRegionsAsyncWithHttpInfo($lang = null, $country = null, $level = null, $population_min = null, $population_max = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listRegions'][0])
    {
        $returnType = '\GeoAPI\Model\RegionListResponse';
        $request = $this->listRegionsRequest($lang, $country, $level, $population_min, $population_max, $cursor, $limit, $fields, $sort, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listRegions'
     *
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $country Filter by ISO alpha-2 country code (optional)
     * @param  int|null $level Filter by administrative level (optional)
     * @param  int|null $population_min Minimum population filter (optional)
     * @param  int|null $population_max Maximum population filter (optional)
     * @param  string|null $cursor Pagination cursor from a previous response (optional)
     * @param  int|null $limit Number of results per page (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string|null $sort Sort field. Allowed: name, population. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listRegions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listRegionsRequest($lang = null, $country = null, $level = null, $population_min = null, $population_max = null, $cursor = null, $limit = 25, $fields = null, $sort = null, string $contentType = self::contentTypes['listRegions'][0])
    {

        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling RegionsApi.listRegions, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling RegionsApi.listRegions, must be bigger than or equal to 2.');
        }
        





        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling RegionsApi.listRegions, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling RegionsApi.listRegions, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/v1/regions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $country,
            'country', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $level,
            'level', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $population_min,
            'population_min', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $population_max,
            'population_max', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation regionChildren
     *
     * List child cities of a region
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['regionChildren'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoAPI\Model\CityListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse
     */
    public function regionChildren($id, $lang = null, $fields = null, string $contentType = self::contentTypes['regionChildren'][0])
    {
        list($response) = $this->regionChildrenWithHttpInfo($id, $lang, $fields, $contentType);
        return $response;
    }

    /**
     * Operation regionChildrenWithHttpInfo
     *
     * List child cities of a region
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['regionChildren'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoAPI\Model\CityListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function regionChildrenWithHttpInfo($id, $lang = null, $fields = null, string $contentType = self::contentTypes['regionChildren'][0])
    {
        $request = $this->regionChildrenRequest($id, $lang, $fields, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\CityListResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoAPI\Model\CityListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\CityListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation regionChildrenAsync
     *
     * List child cities of a region
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['regionChildren'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function regionChildrenAsync($id, $lang = null, $fields = null, string $contentType = self::contentTypes['regionChildren'][0])
    {
        return $this->regionChildrenAsyncWithHttpInfo($id, $lang, $fields, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation regionChildrenAsyncWithHttpInfo
     *
     * List child cities of a region
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['regionChildren'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function regionChildrenAsyncWithHttpInfo($id, $lang = null, $fields = null, string $contentType = self::contentTypes['regionChildren'][0])
    {
        $returnType = '\GeoAPI\Model\CityListResponse';
        $request = $this->regionChildrenRequest($id, $lang, $fields, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'regionChildren'
     *
     * @param  int $id Region ID (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['regionChildren'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function regionChildrenRequest($id, $lang = null, $fields = null, string $contentType = self::contentTypes['regionChildren'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling regionChildren'
            );
        }

        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling RegionsApi.regionChildren, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling RegionsApi.regionChildren, must be bigger than or equal to 2.');
        }
        


        $resourcePath = '/v1/regions/{id}/children';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
