<?php
/**
 * SearchApi
 * PHP version 8.1
 *
 * @category Class
 * @package  GeoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GeoAPI
 *
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GeoAPI\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use GeoAPI\ApiException;
use GeoAPI\Configuration;
use GeoAPI\FormDataProcessor;
use GeoAPI\HeaderSelector;
use GeoAPI\ObjectSerializer;

/**
 * SearchApi Class Doc Comment
 *
 * @category Class
 * @package  GeoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SearchApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'autocomplete' => [
            'application/json',
        ],
        'resolveCoordinate' => [
            'application/json',
        ],
        'reverseGeocode' => [
            'application/json',
        ],
        'search' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation autocomplete
     *
     * Autocomplete search
     *
     * @param  string $q Search query (minimum 2 characters) (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  int|null $limit Maximum results to return (1-25, default 10) (optional, default to 10)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['autocomplete'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoAPI\Model\AutocompleteListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse
     */
    public function autocomplete($q, $lang = null, $limit = 10, $fields = null, string $contentType = self::contentTypes['autocomplete'][0])
    {
        list($response) = $this->autocompleteWithHttpInfo($q, $lang, $limit, $fields, $contentType);
        return $response;
    }

    /**
     * Operation autocompleteWithHttpInfo
     *
     * Autocomplete search
     *
     * @param  string $q Search query (minimum 2 characters) (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  int|null $limit Maximum results to return (1-25, default 10) (optional, default to 10)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['autocomplete'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoAPI\Model\AutocompleteListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function autocompleteWithHttpInfo($q, $lang = null, $limit = 10, $fields = null, string $contentType = self::contentTypes['autocomplete'][0])
    {
        $request = $this->autocompleteRequest($q, $lang, $limit, $fields, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\AutocompleteListResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoAPI\Model\AutocompleteListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\AutocompleteListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation autocompleteAsync
     *
     * Autocomplete search
     *
     * @param  string $q Search query (minimum 2 characters) (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  int|null $limit Maximum results to return (1-25, default 10) (optional, default to 10)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['autocomplete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function autocompleteAsync($q, $lang = null, $limit = 10, $fields = null, string $contentType = self::contentTypes['autocomplete'][0])
    {
        return $this->autocompleteAsyncWithHttpInfo($q, $lang, $limit, $fields, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation autocompleteAsyncWithHttpInfo
     *
     * Autocomplete search
     *
     * @param  string $q Search query (minimum 2 characters) (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  int|null $limit Maximum results to return (1-25, default 10) (optional, default to 10)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['autocomplete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function autocompleteAsyncWithHttpInfo($q, $lang = null, $limit = 10, $fields = null, string $contentType = self::contentTypes['autocomplete'][0])
    {
        $returnType = '\GeoAPI\Model\AutocompleteListResponse';
        $request = $this->autocompleteRequest($q, $lang, $limit, $fields, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'autocomplete'
     *
     * @param  string $q Search query (minimum 2 characters) (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  int|null $limit Maximum results to return (1-25, default 10) (optional, default to 10)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['autocomplete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function autocompleteRequest($q, $lang = null, $limit = 10, $fields = null, string $contentType = self::contentTypes['autocomplete'][0])
    {

        // verify the required parameter 'q' is set
        if ($q === null || (is_array($q) && count($q) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $q when calling autocomplete'
            );
        }
        if (strlen($q) < 2) {
            throw new \InvalidArgumentException('invalid length for "$q" when calling SearchApi.autocomplete, must be bigger than or equal to 2.');
        }
        
        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling SearchApi.autocomplete, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling SearchApi.autocomplete, must be bigger than or equal to 2.');
        }
        
        if ($limit !== null && $limit > 25) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SearchApi.autocomplete, must be smaller than or equal to 25.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SearchApi.autocomplete, must be bigger than or equal to 1.');
        }
        


        $resourcePath = '/v1/autocomplete';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $q,
            'q', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation resolveCoordinate
     *
     * Resolve coordinates to their containing administrative areas
     *
     * @param  float $lat Latitude (-90 to 90). Must be a finite number: &#x60;NaN&#x60; and &#x60;Infinity&#x60; are rejected with a 400 rather than being passed to the spatial index, which would answer them with an ordinary \&quot;not found\&quot;. (required)
     * @param  float $lon Longitude (-180 to 180). Must be a finite number; see &#x60;lat&#x60;. (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resolveCoordinate'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoAPI\Model\HierarchyListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse
     */
    public function resolveCoordinate($lat, $lon, $lang = null, string $contentType = self::contentTypes['resolveCoordinate'][0])
    {
        list($response) = $this->resolveCoordinateWithHttpInfo($lat, $lon, $lang, $contentType);
        return $response;
    }

    /**
     * Operation resolveCoordinateWithHttpInfo
     *
     * Resolve coordinates to their containing administrative areas
     *
     * @param  float $lat Latitude (-90 to 90). Must be a finite number: &#x60;NaN&#x60; and &#x60;Infinity&#x60; are rejected with a 400 rather than being passed to the spatial index, which would answer them with an ordinary \&quot;not found\&quot;. (required)
     * @param  float $lon Longitude (-180 to 180). Must be a finite number; see &#x60;lat&#x60;. (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resolveCoordinate'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoAPI\Model\HierarchyListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function resolveCoordinateWithHttpInfo($lat, $lon, $lang = null, string $contentType = self::contentTypes['resolveCoordinate'][0])
    {
        $request = $this->resolveCoordinateRequest($lat, $lon, $lang, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\HierarchyListResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 503:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoAPI\Model\HierarchyListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\HierarchyListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation resolveCoordinateAsync
     *
     * Resolve coordinates to their containing administrative areas
     *
     * @param  float $lat Latitude (-90 to 90). Must be a finite number: &#x60;NaN&#x60; and &#x60;Infinity&#x60; are rejected with a 400 rather than being passed to the spatial index, which would answer them with an ordinary \&quot;not found\&quot;. (required)
     * @param  float $lon Longitude (-180 to 180). Must be a finite number; see &#x60;lat&#x60;. (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resolveCoordinate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resolveCoordinateAsync($lat, $lon, $lang = null, string $contentType = self::contentTypes['resolveCoordinate'][0])
    {
        return $this->resolveCoordinateAsyncWithHttpInfo($lat, $lon, $lang, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation resolveCoordinateAsyncWithHttpInfo
     *
     * Resolve coordinates to their containing administrative areas
     *
     * @param  float $lat Latitude (-90 to 90). Must be a finite number: &#x60;NaN&#x60; and &#x60;Infinity&#x60; are rejected with a 400 rather than being passed to the spatial index, which would answer them with an ordinary \&quot;not found\&quot;. (required)
     * @param  float $lon Longitude (-180 to 180). Must be a finite number; see &#x60;lat&#x60;. (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resolveCoordinate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resolveCoordinateAsyncWithHttpInfo($lat, $lon, $lang = null, string $contentType = self::contentTypes['resolveCoordinate'][0])
    {
        $returnType = '\GeoAPI\Model\HierarchyListResponse';
        $request = $this->resolveCoordinateRequest($lat, $lon, $lang, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'resolveCoordinate'
     *
     * @param  float $lat Latitude (-90 to 90). Must be a finite number: &#x60;NaN&#x60; and &#x60;Infinity&#x60; are rejected with a 400 rather than being passed to the spatial index, which would answer them with an ordinary \&quot;not found\&quot;. (required)
     * @param  float $lon Longitude (-180 to 180). Must be a finite number; see &#x60;lat&#x60;. (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resolveCoordinate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function resolveCoordinateRequest($lat, $lon, $lang = null, string $contentType = self::contentTypes['resolveCoordinate'][0])
    {

        // verify the required parameter 'lat' is set
        if ($lat === null || (is_array($lat) && count($lat) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lat when calling resolveCoordinate'
            );
        }
        if ($lat > 90) {
            throw new \InvalidArgumentException('invalid value for "$lat" when calling SearchApi.resolveCoordinate, must be smaller than or equal to 90.');
        }
        if ($lat < -90) {
            throw new \InvalidArgumentException('invalid value for "$lat" when calling SearchApi.resolveCoordinate, must be bigger than or equal to -90.');
        }
        
        // verify the required parameter 'lon' is set
        if ($lon === null || (is_array($lon) && count($lon) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lon when calling resolveCoordinate'
            );
        }
        if ($lon > 180) {
            throw new \InvalidArgumentException('invalid value for "$lon" when calling SearchApi.resolveCoordinate, must be smaller than or equal to 180.');
        }
        if ($lon < -180) {
            throw new \InvalidArgumentException('invalid value for "$lon" when calling SearchApi.resolveCoordinate, must be bigger than or equal to -180.');
        }
        
        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling SearchApi.resolveCoordinate, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling SearchApi.resolveCoordinate, must be bigger than or equal to 2.');
        }
        

        $resourcePath = '/v1/resolve';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lat,
            'lat', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lon,
            'lon', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation reverseGeocode
     *
     * Reverse geocode coordinates
     *
     * @param  float $lat Latitude (-90 to 90) (required)
     * @param  float $lon Longitude (-180 to 180) (required)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['reverseGeocode'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoAPI\Model\ReverseGeocodeSingleResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse
     */
    public function reverseGeocode($lat, $lon, $fields = null, string $contentType = self::contentTypes['reverseGeocode'][0])
    {
        list($response) = $this->reverseGeocodeWithHttpInfo($lat, $lon, $fields, $contentType);
        return $response;
    }

    /**
     * Operation reverseGeocodeWithHttpInfo
     *
     * Reverse geocode coordinates
     *
     * @param  float $lat Latitude (-90 to 90) (required)
     * @param  float $lon Longitude (-180 to 180) (required)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['reverseGeocode'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoAPI\Model\ReverseGeocodeSingleResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function reverseGeocodeWithHttpInfo($lat, $lon, $fields = null, string $contentType = self::contentTypes['reverseGeocode'][0])
    {
        $request = $this->reverseGeocodeRequest($lat, $lon, $fields, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ReverseGeocodeSingleResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoAPI\Model\ReverseGeocodeSingleResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ReverseGeocodeSingleResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation reverseGeocodeAsync
     *
     * Reverse geocode coordinates
     *
     * @param  float $lat Latitude (-90 to 90) (required)
     * @param  float $lon Longitude (-180 to 180) (required)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['reverseGeocode'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function reverseGeocodeAsync($lat, $lon, $fields = null, string $contentType = self::contentTypes['reverseGeocode'][0])
    {
        return $this->reverseGeocodeAsyncWithHttpInfo($lat, $lon, $fields, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation reverseGeocodeAsyncWithHttpInfo
     *
     * Reverse geocode coordinates
     *
     * @param  float $lat Latitude (-90 to 90) (required)
     * @param  float $lon Longitude (-180 to 180) (required)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['reverseGeocode'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function reverseGeocodeAsyncWithHttpInfo($lat, $lon, $fields = null, string $contentType = self::contentTypes['reverseGeocode'][0])
    {
        $returnType = '\GeoAPI\Model\ReverseGeocodeSingleResponse';
        $request = $this->reverseGeocodeRequest($lat, $lon, $fields, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'reverseGeocode'
     *
     * @param  float $lat Latitude (-90 to 90) (required)
     * @param  float $lon Longitude (-180 to 180) (required)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['reverseGeocode'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function reverseGeocodeRequest($lat, $lon, $fields = null, string $contentType = self::contentTypes['reverseGeocode'][0])
    {

        // verify the required parameter 'lat' is set
        if ($lat === null || (is_array($lat) && count($lat) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lat when calling reverseGeocode'
            );
        }
        if ($lat > 90) {
            throw new \InvalidArgumentException('invalid value for "$lat" when calling SearchApi.reverseGeocode, must be smaller than or equal to 90.');
        }
        if ($lat < -90) {
            throw new \InvalidArgumentException('invalid value for "$lat" when calling SearchApi.reverseGeocode, must be bigger than or equal to -90.');
        }
        
        // verify the required parameter 'lon' is set
        if ($lon === null || (is_array($lon) && count($lon) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lon when calling reverseGeocode'
            );
        }
        if ($lon > 180) {
            throw new \InvalidArgumentException('invalid value for "$lon" when calling SearchApi.reverseGeocode, must be smaller than or equal to 180.');
        }
        if ($lon < -180) {
            throw new \InvalidArgumentException('invalid value for "$lon" when calling SearchApi.reverseGeocode, must be bigger than or equal to -180.');
        }
        


        $resourcePath = '/v1/reverse';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lat,
            'lat', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lon,
            'lon', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation search
     *
     * Cross-type search
     *
     * @param  string $q Search query (minimum 2 characters) (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $type Filter by entity type (comma-separated). Allowed: country, region, city. (optional)
     * @param  int|null $limit Maximum results to return (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['search'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GeoAPI\Model\SearchListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse
     */
    public function search($q, $lang = null, $type = null, $limit = 25, $fields = null, string $contentType = self::contentTypes['search'][0])
    {
        list($response) = $this->searchWithHttpInfo($q, $lang, $type, $limit, $fields, $contentType);
        return $response;
    }

    /**
     * Operation searchWithHttpInfo
     *
     * Cross-type search
     *
     * @param  string $q Search query (minimum 2 characters) (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $type Filter by entity type (comma-separated). Allowed: country, region, city. (optional)
     * @param  int|null $limit Maximum results to return (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['search'] to see the possible values for this operation
     *
     * @throws \GeoAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GeoAPI\Model\SearchListResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse|\GeoAPI\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchWithHttpInfo($q, $lang = null, $type = null, $limit = 25, $fields = null, string $contentType = self::contentTypes['search'][0])
    {
        $request = $this->searchRequest($q, $lang, $type, $limit, $fields, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\SearchListResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\GeoAPI\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GeoAPI\Model\SearchListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\SearchListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GeoAPI\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation searchAsync
     *
     * Cross-type search
     *
     * @param  string $q Search query (minimum 2 characters) (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $type Filter by entity type (comma-separated). Allowed: country, region, city. (optional)
     * @param  int|null $limit Maximum results to return (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['search'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchAsync($q, $lang = null, $type = null, $limit = 25, $fields = null, string $contentType = self::contentTypes['search'][0])
    {
        return $this->searchAsyncWithHttpInfo($q, $lang, $type, $limit, $fields, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchAsyncWithHttpInfo
     *
     * Cross-type search
     *
     * @param  string $q Search query (minimum 2 characters) (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $type Filter by entity type (comma-separated). Allowed: country, region, city. (optional)
     * @param  int|null $limit Maximum results to return (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['search'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchAsyncWithHttpInfo($q, $lang = null, $type = null, $limit = 25, $fields = null, string $contentType = self::contentTypes['search'][0])
    {
        $returnType = '\GeoAPI\Model\SearchListResponse';
        $request = $this->searchRequest($q, $lang, $type, $limit, $fields, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'search'
     *
     * @param  string $q Search query (minimum 2 characters) (required)
     * @param  string|null $lang ISO 639-1 language code for localized names (e.g., de, fr, ja) (optional)
     * @param  string|null $type Filter by entity type (comma-separated). Allowed: country, region, city. (optional)
     * @param  int|null $limit Maximum results to return (1-100, default 25) (optional, default to 25)
     * @param  string|null $fields Comma-separated list of fields to include in the response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['search'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchRequest($q, $lang = null, $type = null, $limit = 25, $fields = null, string $contentType = self::contentTypes['search'][0])
    {

        // verify the required parameter 'q' is set
        if ($q === null || (is_array($q) && count($q) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $q when calling search'
            );
        }
        if (strlen($q) < 2) {
            throw new \InvalidArgumentException('invalid length for "$q" when calling SearchApi.search, must be bigger than or equal to 2.');
        }
        
        if ($lang !== null && strlen($lang) > 5) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling SearchApi.search, must be smaller than or equal to 5.');
        }
        if ($lang !== null && strlen($lang) < 2) {
            throw new \InvalidArgumentException('invalid length for "$lang" when calling SearchApi.search, must be bigger than or equal to 2.');
        }
        

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SearchApi.search, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SearchApi.search, must be bigger than or equal to 1.');
        }
        


        $resourcePath = '/v1/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lang,
            'lang', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $q,
            'q', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type,
            'type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fields,
            'fields', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
