<?php
/**
 * Country
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GeoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GeoAPI
 *
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GeoAPI\Model;

use \ArrayAccess;
use \GeoAPI\ObjectSerializer;

/**
 * Country Class Doc Comment
 *
 * @category Class
 * @package  GeoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Country implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Country';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'int',
        'geoname_id' => 'int',
        'iso_code' => 'string',
        'iso3_code' => 'string',
        'iso_numeric' => 'int',
        'fips_code' => 'string',
        'name' => 'string',
        'capital' => 'string',
        'area_sq_km' => 'float',
        'population' => 'int',
        'continent_code' => 'string',
        'tld' => 'string',
        'currency_code' => 'string',
        'currency_name' => 'string',
        'phone' => 'string',
        'postal_code_format' => 'string',
        'postal_code_regex' => 'string',
        'languages' => 'string[]',
        'neighbours' => 'string[]',
        'latitude' => 'float',
        'longitude' => 'float',
        'flag_emoji' => 'string',
        'geometry' => '\GeoAPI\Model\GeoJSONMultiPolygon'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'geoname_id' => 'int64',
        'iso_code' => null,
        'iso3_code' => null,
        'iso_numeric' => null,
        'fips_code' => null,
        'name' => null,
        'capital' => null,
        'area_sq_km' => 'double',
        'population' => 'int64',
        'continent_code' => null,
        'tld' => null,
        'currency_code' => null,
        'currency_name' => null,
        'phone' => null,
        'postal_code_format' => null,
        'postal_code_regex' => null,
        'languages' => null,
        'neighbours' => null,
        'latitude' => 'double',
        'longitude' => 'double',
        'flag_emoji' => null,
        'geometry' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'geoname_id' => false,
        'iso_code' => false,
        'iso3_code' => false,
        'iso_numeric' => false,
        'fips_code' => false,
        'name' => false,
        'capital' => false,
        'area_sq_km' => false,
        'population' => false,
        'continent_code' => false,
        'tld' => false,
        'currency_code' => false,
        'currency_name' => false,
        'phone' => false,
        'postal_code_format' => false,
        'postal_code_regex' => false,
        'languages' => false,
        'neighbours' => false,
        'latitude' => false,
        'longitude' => false,
        'flag_emoji' => false,
        'geometry' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'geoname_id' => 'geoname_id',
        'iso_code' => 'iso_code',
        'iso3_code' => 'iso3_code',
        'iso_numeric' => 'iso_numeric',
        'fips_code' => 'fips_code',
        'name' => 'name',
        'capital' => 'capital',
        'area_sq_km' => 'area_sq_km',
        'population' => 'population',
        'continent_code' => 'continent_code',
        'tld' => 'tld',
        'currency_code' => 'currency_code',
        'currency_name' => 'currency_name',
        'phone' => 'phone',
        'postal_code_format' => 'postal_code_format',
        'postal_code_regex' => 'postal_code_regex',
        'languages' => 'languages',
        'neighbours' => 'neighbours',
        'latitude' => 'latitude',
        'longitude' => 'longitude',
        'flag_emoji' => 'flag_emoji',
        'geometry' => 'geometry'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'geoname_id' => 'setGeonameId',
        'iso_code' => 'setIsoCode',
        'iso3_code' => 'setIso3Code',
        'iso_numeric' => 'setIsoNumeric',
        'fips_code' => 'setFipsCode',
        'name' => 'setName',
        'capital' => 'setCapital',
        'area_sq_km' => 'setAreaSqKm',
        'population' => 'setPopulation',
        'continent_code' => 'setContinentCode',
        'tld' => 'setTld',
        'currency_code' => 'setCurrencyCode',
        'currency_name' => 'setCurrencyName',
        'phone' => 'setPhone',
        'postal_code_format' => 'setPostalCodeFormat',
        'postal_code_regex' => 'setPostalCodeRegex',
        'languages' => 'setLanguages',
        'neighbours' => 'setNeighbours',
        'latitude' => 'setLatitude',
        'longitude' => 'setLongitude',
        'flag_emoji' => 'setFlagEmoji',
        'geometry' => 'setGeometry'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'geoname_id' => 'getGeonameId',
        'iso_code' => 'getIsoCode',
        'iso3_code' => 'getIso3Code',
        'iso_numeric' => 'getIsoNumeric',
        'fips_code' => 'getFipsCode',
        'name' => 'getName',
        'capital' => 'getCapital',
        'area_sq_km' => 'getAreaSqKm',
        'population' => 'getPopulation',
        'continent_code' => 'getContinentCode',
        'tld' => 'getTld',
        'currency_code' => 'getCurrencyCode',
        'currency_name' => 'getCurrencyName',
        'phone' => 'getPhone',
        'postal_code_format' => 'getPostalCodeFormat',
        'postal_code_regex' => 'getPostalCodeRegex',
        'languages' => 'getLanguages',
        'neighbours' => 'getNeighbours',
        'latitude' => 'getLatitude',
        'longitude' => 'getLongitude',
        'flag_emoji' => 'getFlagEmoji',
        'geometry' => 'getGeometry'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('geoname_id', $data ?? [], null);
        $this->setIfExists('iso_code', $data ?? [], null);
        $this->setIfExists('iso3_code', $data ?? [], null);
        $this->setIfExists('iso_numeric', $data ?? [], null);
        $this->setIfExists('fips_code', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('capital', $data ?? [], null);
        $this->setIfExists('area_sq_km', $data ?? [], null);
        $this->setIfExists('population', $data ?? [], null);
        $this->setIfExists('continent_code', $data ?? [], null);
        $this->setIfExists('tld', $data ?? [], null);
        $this->setIfExists('currency_code', $data ?? [], null);
        $this->setIfExists('currency_name', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('postal_code_format', $data ?? [], null);
        $this->setIfExists('postal_code_regex', $data ?? [], null);
        $this->setIfExists('languages', $data ?? [], null);
        $this->setIfExists('neighbours', $data ?? [], null);
        $this->setIfExists('latitude', $data ?? [], null);
        $this->setIfExists('longitude', $data ?? [], null);
        $this->setIfExists('flag_emoji', $data ?? [], null);
        $this->setIfExists('geometry', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets geoname_id
     *
     * @return int|null
     */
    public function getGeonameId()
    {
        return $this->container['geoname_id'];
    }

    /**
     * Sets geoname_id
     *
     * @param int|null $geoname_id geoname_id
     *
     * @return self
     */
    public function setGeonameId($geoname_id)
    {
        if (is_null($geoname_id)) {
            throw new \InvalidArgumentException('non-nullable geoname_id cannot be null');
        }
        $this->container['geoname_id'] = $geoname_id;

        return $this;
    }

    /**
     * Gets iso_code
     *
     * @return string|null
     */
    public function getIsoCode()
    {
        return $this->container['iso_code'];
    }

    /**
     * Sets iso_code
     *
     * @param string|null $iso_code iso_code
     *
     * @return self
     */
    public function setIsoCode($iso_code)
    {
        if (is_null($iso_code)) {
            throw new \InvalidArgumentException('non-nullable iso_code cannot be null');
        }
        $this->container['iso_code'] = $iso_code;

        return $this;
    }

    /**
     * Gets iso3_code
     *
     * @return string|null
     */
    public function getIso3Code()
    {
        return $this->container['iso3_code'];
    }

    /**
     * Sets iso3_code
     *
     * @param string|null $iso3_code iso3_code
     *
     * @return self
     */
    public function setIso3Code($iso3_code)
    {
        if (is_null($iso3_code)) {
            throw new \InvalidArgumentException('non-nullable iso3_code cannot be null');
        }
        $this->container['iso3_code'] = $iso3_code;

        return $this;
    }

    /**
     * Gets iso_numeric
     *
     * @return int|null
     */
    public function getIsoNumeric()
    {
        return $this->container['iso_numeric'];
    }

    /**
     * Sets iso_numeric
     *
     * @param int|null $iso_numeric iso_numeric
     *
     * @return self
     */
    public function setIsoNumeric($iso_numeric)
    {
        if (is_null($iso_numeric)) {
            throw new \InvalidArgumentException('non-nullable iso_numeric cannot be null');
        }
        $this->container['iso_numeric'] = $iso_numeric;

        return $this;
    }

    /**
     * Gets fips_code
     *
     * @return string|null
     */
    public function getFipsCode()
    {
        return $this->container['fips_code'];
    }

    /**
     * Sets fips_code
     *
     * @param string|null $fips_code fips_code
     *
     * @return self
     */
    public function setFipsCode($fips_code)
    {
        if (is_null($fips_code)) {
            throw new \InvalidArgumentException('non-nullable fips_code cannot be null');
        }
        $this->container['fips_code'] = $fips_code;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets capital
     *
     * @return string|null
     */
    public function getCapital()
    {
        return $this->container['capital'];
    }

    /**
     * Sets capital
     *
     * @param string|null $capital capital
     *
     * @return self
     */
    public function setCapital($capital)
    {
        if (is_null($capital)) {
            throw new \InvalidArgumentException('non-nullable capital cannot be null');
        }
        $this->container['capital'] = $capital;

        return $this;
    }

    /**
     * Gets area_sq_km
     *
     * @return float|null
     */
    public function getAreaSqKm()
    {
        return $this->container['area_sq_km'];
    }

    /**
     * Sets area_sq_km
     *
     * @param float|null $area_sq_km area_sq_km
     *
     * @return self
     */
    public function setAreaSqKm($area_sq_km)
    {
        if (is_null($area_sq_km)) {
            throw new \InvalidArgumentException('non-nullable area_sq_km cannot be null');
        }
        $this->container['area_sq_km'] = $area_sq_km;

        return $this;
    }

    /**
     * Gets population
     *
     * @return int|null
     */
    public function getPopulation()
    {
        return $this->container['population'];
    }

    /**
     * Sets population
     *
     * @param int|null $population population
     *
     * @return self
     */
    public function setPopulation($population)
    {
        if (is_null($population)) {
            throw new \InvalidArgumentException('non-nullable population cannot be null');
        }
        $this->container['population'] = $population;

        return $this;
    }

    /**
     * Gets continent_code
     *
     * @return string|null
     */
    public function getContinentCode()
    {
        return $this->container['continent_code'];
    }

    /**
     * Sets continent_code
     *
     * @param string|null $continent_code continent_code
     *
     * @return self
     */
    public function setContinentCode($continent_code)
    {
        if (is_null($continent_code)) {
            throw new \InvalidArgumentException('non-nullable continent_code cannot be null');
        }
        $this->container['continent_code'] = $continent_code;

        return $this;
    }

    /**
     * Gets tld
     *
     * @return string|null
     */
    public function getTld()
    {
        return $this->container['tld'];
    }

    /**
     * Sets tld
     *
     * @param string|null $tld tld
     *
     * @return self
     */
    public function setTld($tld)
    {
        if (is_null($tld)) {
            throw new \InvalidArgumentException('non-nullable tld cannot be null');
        }
        $this->container['tld'] = $tld;

        return $this;
    }

    /**
     * Gets currency_code
     *
     * @return string|null
     */
    public function getCurrencyCode()
    {
        return $this->container['currency_code'];
    }

    /**
     * Sets currency_code
     *
     * @param string|null $currency_code currency_code
     *
     * @return self
     */
    public function setCurrencyCode($currency_code)
    {
        if (is_null($currency_code)) {
            throw new \InvalidArgumentException('non-nullable currency_code cannot be null');
        }
        $this->container['currency_code'] = $currency_code;

        return $this;
    }

    /**
     * Gets currency_name
     *
     * @return string|null
     */
    public function getCurrencyName()
    {
        return $this->container['currency_name'];
    }

    /**
     * Sets currency_name
     *
     * @param string|null $currency_name currency_name
     *
     * @return self
     */
    public function setCurrencyName($currency_name)
    {
        if (is_null($currency_name)) {
            throw new \InvalidArgumentException('non-nullable currency_name cannot be null');
        }
        $this->container['currency_name'] = $currency_name;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone phone
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets postal_code_format
     *
     * @return string|null
     */
    public function getPostalCodeFormat()
    {
        return $this->container['postal_code_format'];
    }

    /**
     * Sets postal_code_format
     *
     * @param string|null $postal_code_format postal_code_format
     *
     * @return self
     */
    public function setPostalCodeFormat($postal_code_format)
    {
        if (is_null($postal_code_format)) {
            throw new \InvalidArgumentException('non-nullable postal_code_format cannot be null');
        }
        $this->container['postal_code_format'] = $postal_code_format;

        return $this;
    }

    /**
     * Gets postal_code_regex
     *
     * @return string|null
     */
    public function getPostalCodeRegex()
    {
        return $this->container['postal_code_regex'];
    }

    /**
     * Sets postal_code_regex
     *
     * @param string|null $postal_code_regex postal_code_regex
     *
     * @return self
     */
    public function setPostalCodeRegex($postal_code_regex)
    {
        if (is_null($postal_code_regex)) {
            throw new \InvalidArgumentException('non-nullable postal_code_regex cannot be null');
        }
        $this->container['postal_code_regex'] = $postal_code_regex;

        return $this;
    }

    /**
     * Gets languages
     *
     * @return string[]|null
     */
    public function getLanguages()
    {
        return $this->container['languages'];
    }

    /**
     * Sets languages
     *
     * @param string[]|null $languages languages
     *
     * @return self
     */
    public function setLanguages($languages)
    {
        if (is_null($languages)) {
            throw new \InvalidArgumentException('non-nullable languages cannot be null');
        }
        $this->container['languages'] = $languages;

        return $this;
    }

    /**
     * Gets neighbours
     *
     * @return string[]|null
     */
    public function getNeighbours()
    {
        return $this->container['neighbours'];
    }

    /**
     * Sets neighbours
     *
     * @param string[]|null $neighbours neighbours
     *
     * @return self
     */
    public function setNeighbours($neighbours)
    {
        if (is_null($neighbours)) {
            throw new \InvalidArgumentException('non-nullable neighbours cannot be null');
        }
        $this->container['neighbours'] = $neighbours;

        return $this;
    }

    /**
     * Gets latitude
     *
     * @return float|null
     */
    public function getLatitude()
    {
        return $this->container['latitude'];
    }

    /**
     * Sets latitude
     *
     * @param float|null $latitude latitude
     *
     * @return self
     */
    public function setLatitude($latitude)
    {
        if (is_null($latitude)) {
            throw new \InvalidArgumentException('non-nullable latitude cannot be null');
        }
        $this->container['latitude'] = $latitude;

        return $this;
    }

    /**
     * Gets longitude
     *
     * @return float|null
     */
    public function getLongitude()
    {
        return $this->container['longitude'];
    }

    /**
     * Sets longitude
     *
     * @param float|null $longitude longitude
     *
     * @return self
     */
    public function setLongitude($longitude)
    {
        if (is_null($longitude)) {
            throw new \InvalidArgumentException('non-nullable longitude cannot be null');
        }
        $this->container['longitude'] = $longitude;

        return $this;
    }

    /**
     * Gets flag_emoji
     *
     * @return string|null
     */
    public function getFlagEmoji()
    {
        return $this->container['flag_emoji'];
    }

    /**
     * Sets flag_emoji
     *
     * @param string|null $flag_emoji flag_emoji
     *
     * @return self
     */
    public function setFlagEmoji($flag_emoji)
    {
        if (is_null($flag_emoji)) {
            throw new \InvalidArgumentException('non-nullable flag_emoji cannot be null');
        }
        $this->container['flag_emoji'] = $flag_emoji;

        return $this;
    }

    /**
     * Gets geometry
     *
     * @return \GeoAPI\Model\GeoJSONMultiPolygon|null
     */
    public function getGeometry()
    {
        return $this->container['geometry'];
    }

    /**
     * Sets geometry
     *
     * @param \GeoAPI\Model\GeoJSONMultiPolygon|null $geometry Country boundary. Returned by default on `GET /v1/countries/{code}` and on request via `?fields=geometry` on `GET /v1/countries`.  NOT TIER-GATED. Country geometry is served on every plan, including Free. Region geometry is gated — see the `Region` schema.
     *
     * @return self
     */
    public function setGeometry($geometry)
    {
        if (is_null($geometry)) {
            throw new \InvalidArgumentException('non-nullable geometry cannot be null');
        }
        $this->container['geometry'] = $geometry;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


