<?php
/**
 * PostalCode
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GeoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GeoAPI
 *
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GeoAPI\Model;

use \ArrayAccess;
use \GeoAPI\ObjectSerializer;

/**
 * PostalCode Class Doc Comment
 *
 * @category Class
 * @package  GeoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PostalCode implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PostalCode';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'int',
        'country_code' => 'string',
        'postal_code' => 'string',
        'place_name' => 'string',
        'admin_name1' => 'string',
        'admin_code1' => 'string',
        'admin_name2' => 'string',
        'admin_code2' => 'string',
        'admin_name3' => 'string',
        'admin_code3' => 'string',
        'latitude' => 'float',
        'longitude' => 'float',
        'accuracy' => 'int',
        'country' => '\GeoAPI\Model\CountryRef'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'country_code' => null,
        'postal_code' => null,
        'place_name' => null,
        'admin_name1' => null,
        'admin_code1' => null,
        'admin_name2' => null,
        'admin_code2' => null,
        'admin_name3' => null,
        'admin_code3' => null,
        'latitude' => 'double',
        'longitude' => 'double',
        'accuracy' => null,
        'country' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'country_code' => false,
        'postal_code' => false,
        'place_name' => false,
        'admin_name1' => false,
        'admin_code1' => false,
        'admin_name2' => false,
        'admin_code2' => false,
        'admin_name3' => false,
        'admin_code3' => false,
        'latitude' => false,
        'longitude' => false,
        'accuracy' => false,
        'country' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'country_code' => 'country_code',
        'postal_code' => 'postal_code',
        'place_name' => 'place_name',
        'admin_name1' => 'admin_name1',
        'admin_code1' => 'admin_code1',
        'admin_name2' => 'admin_name2',
        'admin_code2' => 'admin_code2',
        'admin_name3' => 'admin_name3',
        'admin_code3' => 'admin_code3',
        'latitude' => 'latitude',
        'longitude' => 'longitude',
        'accuracy' => 'accuracy',
        'country' => 'country'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'country_code' => 'setCountryCode',
        'postal_code' => 'setPostalCode',
        'place_name' => 'setPlaceName',
        'admin_name1' => 'setAdminName1',
        'admin_code1' => 'setAdminCode1',
        'admin_name2' => 'setAdminName2',
        'admin_code2' => 'setAdminCode2',
        'admin_name3' => 'setAdminName3',
        'admin_code3' => 'setAdminCode3',
        'latitude' => 'setLatitude',
        'longitude' => 'setLongitude',
        'accuracy' => 'setAccuracy',
        'country' => 'setCountry'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'country_code' => 'getCountryCode',
        'postal_code' => 'getPostalCode',
        'place_name' => 'getPlaceName',
        'admin_name1' => 'getAdminName1',
        'admin_code1' => 'getAdminCode1',
        'admin_name2' => 'getAdminName2',
        'admin_code2' => 'getAdminCode2',
        'admin_name3' => 'getAdminName3',
        'admin_code3' => 'getAdminCode3',
        'latitude' => 'getLatitude',
        'longitude' => 'getLongitude',
        'accuracy' => 'getAccuracy',
        'country' => 'getCountry'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('country_code', $data ?? [], null);
        $this->setIfExists('postal_code', $data ?? [], null);
        $this->setIfExists('place_name', $data ?? [], null);
        $this->setIfExists('admin_name1', $data ?? [], null);
        $this->setIfExists('admin_code1', $data ?? [], null);
        $this->setIfExists('admin_name2', $data ?? [], null);
        $this->setIfExists('admin_code2', $data ?? [], null);
        $this->setIfExists('admin_name3', $data ?? [], null);
        $this->setIfExists('admin_code3', $data ?? [], null);
        $this->setIfExists('latitude', $data ?? [], null);
        $this->setIfExists('longitude', $data ?? [], null);
        $this->setIfExists('accuracy', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets country_code
     *
     * @return string|null
     */
    public function getCountryCode()
    {
        return $this->container['country_code'];
    }

    /**
     * Sets country_code
     *
     * @param string|null $country_code country_code
     *
     * @return self
     */
    public function setCountryCode($country_code)
    {
        if (is_null($country_code)) {
            throw new \InvalidArgumentException('non-nullable country_code cannot be null');
        }
        $this->container['country_code'] = $country_code;

        return $this;
    }

    /**
     * Gets postal_code
     *
     * @return string|null
     */
    public function getPostalCode()
    {
        return $this->container['postal_code'];
    }

    /**
     * Sets postal_code
     *
     * @param string|null $postal_code postal_code
     *
     * @return self
     */
    public function setPostalCode($postal_code)
    {
        if (is_null($postal_code)) {
            throw new \InvalidArgumentException('non-nullable postal_code cannot be null');
        }
        $this->container['postal_code'] = $postal_code;

        return $this;
    }

    /**
     * Gets place_name
     *
     * @return string|null
     */
    public function getPlaceName()
    {
        return $this->container['place_name'];
    }

    /**
     * Sets place_name
     *
     * @param string|null $place_name place_name
     *
     * @return self
     */
    public function setPlaceName($place_name)
    {
        if (is_null($place_name)) {
            throw new \InvalidArgumentException('non-nullable place_name cannot be null');
        }
        $this->container['place_name'] = $place_name;

        return $this;
    }

    /**
     * Gets admin_name1
     *
     * @return string|null
     */
    public function getAdminName1()
    {
        return $this->container['admin_name1'];
    }

    /**
     * Sets admin_name1
     *
     * @param string|null $admin_name1 admin_name1
     *
     * @return self
     */
    public function setAdminName1($admin_name1)
    {
        if (is_null($admin_name1)) {
            throw new \InvalidArgumentException('non-nullable admin_name1 cannot be null');
        }
        $this->container['admin_name1'] = $admin_name1;

        return $this;
    }

    /**
     * Gets admin_code1
     *
     * @return string|null
     */
    public function getAdminCode1()
    {
        return $this->container['admin_code1'];
    }

    /**
     * Sets admin_code1
     *
     * @param string|null $admin_code1 admin_code1
     *
     * @return self
     */
    public function setAdminCode1($admin_code1)
    {
        if (is_null($admin_code1)) {
            throw new \InvalidArgumentException('non-nullable admin_code1 cannot be null');
        }
        $this->container['admin_code1'] = $admin_code1;

        return $this;
    }

    /**
     * Gets admin_name2
     *
     * @return string|null
     */
    public function getAdminName2()
    {
        return $this->container['admin_name2'];
    }

    /**
     * Sets admin_name2
     *
     * @param string|null $admin_name2 admin_name2
     *
     * @return self
     */
    public function setAdminName2($admin_name2)
    {
        if (is_null($admin_name2)) {
            throw new \InvalidArgumentException('non-nullable admin_name2 cannot be null');
        }
        $this->container['admin_name2'] = $admin_name2;

        return $this;
    }

    /**
     * Gets admin_code2
     *
     * @return string|null
     */
    public function getAdminCode2()
    {
        return $this->container['admin_code2'];
    }

    /**
     * Sets admin_code2
     *
     * @param string|null $admin_code2 admin_code2
     *
     * @return self
     */
    public function setAdminCode2($admin_code2)
    {
        if (is_null($admin_code2)) {
            throw new \InvalidArgumentException('non-nullable admin_code2 cannot be null');
        }
        $this->container['admin_code2'] = $admin_code2;

        return $this;
    }

    /**
     * Gets admin_name3
     *
     * @return string|null
     */
    public function getAdminName3()
    {
        return $this->container['admin_name3'];
    }

    /**
     * Sets admin_name3
     *
     * @param string|null $admin_name3 admin_name3
     *
     * @return self
     */
    public function setAdminName3($admin_name3)
    {
        if (is_null($admin_name3)) {
            throw new \InvalidArgumentException('non-nullable admin_name3 cannot be null');
        }
        $this->container['admin_name3'] = $admin_name3;

        return $this;
    }

    /**
     * Gets admin_code3
     *
     * @return string|null
     */
    public function getAdminCode3()
    {
        return $this->container['admin_code3'];
    }

    /**
     * Sets admin_code3
     *
     * @param string|null $admin_code3 admin_code3
     *
     * @return self
     */
    public function setAdminCode3($admin_code3)
    {
        if (is_null($admin_code3)) {
            throw new \InvalidArgumentException('non-nullable admin_code3 cannot be null');
        }
        $this->container['admin_code3'] = $admin_code3;

        return $this;
    }

    /**
     * Gets latitude
     *
     * @return float|null
     */
    public function getLatitude()
    {
        return $this->container['latitude'];
    }

    /**
     * Sets latitude
     *
     * @param float|null $latitude latitude
     *
     * @return self
     */
    public function setLatitude($latitude)
    {
        if (is_null($latitude)) {
            throw new \InvalidArgumentException('non-nullable latitude cannot be null');
        }
        $this->container['latitude'] = $latitude;

        return $this;
    }

    /**
     * Gets longitude
     *
     * @return float|null
     */
    public function getLongitude()
    {
        return $this->container['longitude'];
    }

    /**
     * Sets longitude
     *
     * @param float|null $longitude longitude
     *
     * @return self
     */
    public function setLongitude($longitude)
    {
        if (is_null($longitude)) {
            throw new \InvalidArgumentException('non-nullable longitude cannot be null');
        }
        $this->container['longitude'] = $longitude;

        return $this;
    }

    /**
     * Gets accuracy
     *
     * @return int|null
     */
    public function getAccuracy()
    {
        return $this->container['accuracy'];
    }

    /**
     * Sets accuracy
     *
     * @param int|null $accuracy accuracy
     *
     * @return self
     */
    public function setAccuracy($accuracy)
    {
        if (is_null($accuracy)) {
            throw new \InvalidArgumentException('non-nullable accuracy cannot be null');
        }
        $this->container['accuracy'] = $accuracy;

        return $this;
    }

    /**
     * Gets country
     *
     * @return \GeoAPI\Model\CountryRef|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param \GeoAPI\Model\CountryRef|null $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


