<?php
/**
 * GeoJSONMultiPolygonTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GeoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GeoAPI
 *
 * Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GeoAPI\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GeoJSONMultiPolygonTest Class Doc Comment
 *
 * @category    Class
 * @description GeoJSON MultiPolygon geometry.  WHEN IT IS RETURNED DEPENDS ON THE ENDPOINT AND ON THE PLAN, and there is no single rule. The previous wording here — \&quot;only returned when explicitly requested via &#x60;?fields&#x3D;geometry&#x60;\&quot; — was false in both directions and is corrected below.  &#x60;GET /v1/countries/{code}&#x60; and &#x60;GET /v1/regions/{id}&#x60;: returned by default. These are detail endpoints and they have always served geometry without &#x60;?fields&#x3D;geometry&#x60; being present.  &#x60;GET /v1/countries&#x60;, &#x60;GET /v1/regions&#x60; and &#x60;GET /v1/countries/{code}/regions&#x60;: returned only when &#x60;?fields&#x3D;geometry&#x60; is requested. Omitting it from a list response is a payload decision — a 100-row page of region polygons is several megabytes.  REGION GEOMETRY ADDITIONALLY REQUIRES A PAID PLAN. On &#x60;GET /v1/regions/{id}&#x60;, &#x60;GET /v1/regions?fields&#x3D;geometry&#x60; and &#x60;GET /v1/countries/{code}/regions?fields&#x3D;geometry&#x60;, the &#x60;geometry&#x60; key is OMITTED ENTIRELY for Free-tier keys — absent, not null. Country geometry is not gated: &#x60;GET /v1/countries/{code}&#x60; and &#x60;GET /v1/countries?fields&#x3D;geometry&#x60; serve it on every plan, including Free.  The omission is silent by design: it is not an error, and these endpoints still return 200. A client that reads &#x60;data.geometry.type&#x60; without checking for the key will fail on a null dereference rather than receive a typed zero. To fetch a boundary polygon explicitly — and to receive a 403 with an upgrade link rather than a silent omission when the plan does not include it — use &#x60;GET /v1/boundaries/{geoname_id}&#x60;.
 * @package     GeoAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GeoJSONMultiPolygonTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GeoJSONMultiPolygon"
     */
    public function testGeoJSONMultiPolygon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "coordinates"
     */
    public function testPropertyCoordinates()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
